import Head from "next/head";
import { NextPageContext } from "next";
import { getSession, signOut } from "next-auth/react";
import useCurrentUser from "@/hooks/useCurrentUser";

export async function getServerSideProps(context: NextPageContext) {
  const session = await getSession(context);

  if (!session) {
    return {
      redirect: {
        destination: "/auth",
        permanent: false,
      },
    };
  }
  return {
    props: {},
  };
}

export default function Home() {

  const { data: user} = useCurrentUser()
  return (
    <>
      <Head>
        <title>Netflix</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="flex justify-between items-center py-4">
          <h1 className="text-red-400 text-3xl">welcome</h1>
          <h2 className="text-white">welcome to netflix {user?.name} and {user?.email}</h2>
          <button onClick={() => signOut()} className="bg-white p-3 rounded-md">Log Out</button>
        </div>
      </main>
    </>
  );
}
